spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: devdb_rw
    password: Y8b0nvh0685)D6R
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update